Language="VBSCRIPT"

Sub CATMain()

Set documents1 = CATIA.Documents

Set partDocument1 = documents1.Open("C:\Users\samue\Desktop\Estrutura_menos_rigida\Bumper_two.CATPart")

Set part1 = partDocument1.Part

Set parameters1 = part1.Parameters

Set length1 = parameters1.Item("Front_Bumper")

length1.Value = 600.000000

Set parameters2 = part1.Parameters

Set length2 = parameters2.Item("Real_Raio_Bumper")

length2.Value = 3000.000000

Set parameters3 = part1.Parameters

Set length3 = parameters3.Item("Comprimento_bumper_total")

length3.Value = 350.000000

Set parameters4 = part1.Parameters

Set length4 = parameters4.Item("Largura_Bumper")

length4.Value = 30.000000

Set parameters5 = part1.Parameters

Set length5 = parameters5.Item("Part1\\Distance_Between_Crashes")

length5.Value = 340.000000

Set parameters6 = part1.Parameters

Set length6 = parameters6.Item("Part1\\Altura_Crash")

length6.Value = 50.000000

Set parameters7 = part1.Parameters

Set length7 = parameters7.Item("Part1\\Largura_Crash")

length7.Value = 45.000000

Set parameters8 = part1.Parameters

Set length8 = parameters8.Item("Part1\\Altura_Bumper")

length8.Value = 60.000000

part1.Update 

Set bodies1 = part1.Bodies

Set body1 = bodies1.Item("PartBody")

Set sketches1 = body1.Sketches

Set sketch1 = sketches1.Item("Sketch.1")

Set constraints1 = sketch1.Constraints

Set constraint1 = constraints1.Item("Angle.65")

constraint1.AngleSector = catCstAngleSector3

Set sketch2 = sketches1.Item("Sketch.2")

Set constraints2 = sketch2.Constraints

Set constraint2 = constraints2.Item("Angle.10")

constraint2.AngleSector = catCstAngleSector0

Set angle1 = constraint2.Dimension

angle1.Value = 30.000000

Set constraint3 = constraints2.Item("Angle.14")

constraint3.AngleSector = catCstAngleSector2

Set angle2 = constraint3.Dimension

angle2.Value = 120.000000

Set constraint4 = constraints2.Item("Angle.16")

constraint4.AngleSector = catCstAngleSector1

Set angle3 = constraint4.Dimension

angle3.Value = 120.000000

Set constraint5 = constraints2.Item("Angle.18")

constraint5.AngleSector = catCstAngleSector1

Set angle4 = constraint5.Dimension

angle4.Value = 120.000000

Set partDocument1 = CATIA.ActiveDocument

partDocument1.Save 

Set partDocument1 = CATIA.ActiveDocument

partDocument1.ExportData "C:\Users\samue\Desktop\Estrutura_menos_rigida\Bumper_two.igs", "igs"

End Sub
